### ISSUE TITLE
Gk work

### ISSUE THREAD

**Issue by Mr-Silenz** [KIPASGTS/Mass-cash-bussid#1]
Kok gabisa di run bg ad yg salah

**Comment by ferlitopym** [comment]
lu yg gabisa berarti :v
gw bisa kok aokwoakw

**Comment by Mr-Silenz** [comment]
Run ny python bussid.py kan

**Comment by Eagle299** [comment]
Kalau gak work mungkin faktor dosa

Pada tanggal Min, 17 Jul 2022 20.08, Mr-Silenz ***@***.***>
menulis:
